import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextProviders } from "./provider";
import { Navbar } from "@/components/header";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={inter.className}>
        <StoreProvider>
          <NextProviders>
            <Navbar />
            <main className="">{children}</main>
          </NextProviders>
        </StoreProvider>
      </body>
    </html>
  );
}
